### ISSUE TITLE
Issue with Bronze Dust Recipt

### ISSUE THREAD

**Issue by Norrox** [Chuunkyz/BenchmarkII-1.18#10]
I think there is a issue with the bronze dust recipt, you cant craft one bronse dust with copper and thin, you have to use modern industrial alloy furnace to combine ingots to bronze

**Comment by Chuunkyz** [comment]
making the dust in a crafting table was an easy recipe so i disabled it
the thing is, i used the unification from benchmark 1, indrev isn't for 1.18 atm, and tech reborn removed dust for copper, tin and metals that have raw variants, so mi is the only way to get it
don't worry tho, indrev will be ported to 1.18 soon

**Comment by Norrox** [comment]
cool, i compiled a test version of indrev 1.18 and it worked fine for the most part
