### ISSUE TITLE
world corruption/startup failure after update to v. 1.0.5

### ISSUE THREAD

**Issue by Jordan231111** [Chuunkyz/BenchmarkII-1.18#100]
This message after updating to 1.0.5 on single player world. If proceed it then I get this following error.

![image](https://user-images.githubusercontent.com/79342877/160733204-4148b0da-3c90-4b52-9331-aee8f3b52672.png)

![image](https://user-images.githubusercontent.com/79342877/160733320-7050d006-8137-4d43-9181-1fb6931671b6.png)

**Comment by Chuunkyz** [comment]
you have to reset the nether

**Comment by Jordan231111** [comment]
ok thanks, a suggestion would be to put more important changelog in bold and at the top cuz i read it fast and didnt see it lol.

**Comment by ThornerUA** [comment]
Hello, I have the same issue I reset the nether by deleting the Dim-1 folder and it did nothing, any suggestions?

**Comment by Jordan231111** [comment]
perhaps use the backup and deleting it there
