### ISSUE TITLE
Game crashes when trying to render an item in the creative menu

### ISSUE THREAD

**Issue by shaksternano** [Chuunkyz/BenchmarkII-1.18#11]
0.3.3 fresh world

If you navigate to the search tab in the creative menu and scroll down slowly, the game will crash when you reach approximately halfway.

[latest.log](https://github.com/Chuunkyz/BenchmarkII-1.18/files/7722477/latest.log)

**Comment by Chuunkyz** [comment]
that's due to entity banners, the banners related to mythic mounts are crashing the game on client
the config doesnt work on servers, so i can't really remove the banners, otherwise you'll be kicked of any server.
