### ISSUE TITLE
The modpack crashes because it's out of memory

### ISSUE THREAD

**Issue by alinrabulea** [Chuunkyz/BenchmarkII-1.18#14]
The modpack randomly crashes after playing for 1-2 hours because it's out of memory. I allocated 8 gb of ram. I really think that's enough memory to run the modpack.

**Comment by Chuunkyz** [comment]
your issue is weird
send the crash log, also be sure to not allocate more than 4gb, it's enough !

**Comment by alinrabulea** [comment]
> your issue is weird send the crash log, also be sure to not allocate more than 4gb, it's enough !

Oh and I forgot to mention that it's only happening when a mob is attacking me!
[hs_err_pid9016.log](https://github.com/Chuunkyz/BenchmarkII-1.18/files/7750647/hs_err_pid9016.log)
!
