### ISSUE TITLE
spatial harvesters mod crashes the game when you break a harvester

### ISSUE THREAD

**Issue by internet-person** [Chuunkyz/BenchmarkII-1.18#15]
breaking harvesters crashes the host, this issue happens both in multi and single player. also as far as i can tell this mod is only updated for 1.17.1.

**Comment by Chuunkyz** [comment]
will be fixed in next spatial harvesters update

**Comment by Dunkmania101** [comment]
> I released two new jars, one for 1.17.x and one for 1.18.x, both labeled as 0.11.12d. Please let me know if something's still broken!

I figured I should copy this message to here so internet-person could see it more easily.
