### ISSUE TITLE
"Server closed" when generating Nether on a single player world.

### ISSUE THREAD

**Issue by synewave** [Chuunkyz/BenchmarkII-1.18#17]
World exits out to the server list when entering a nether portal for the first time. Trying to enter again without deleting the "DIM-1" folder crashes the world.

[Log](https://paste.ee/p/IgRyz)

**Comment by Werneq** [comment]
Can relate and reproduce, just trying to enter on nether and game close to the server list

**Comment by ShawnKilbride** [comment]
I'm also experiencing this issue.

**Comment by Werneq** [comment]
Just to register, still with this problem on 0.4.2

**Comment by Werneq** [comment]
This problem is related with BetterNether mod, and I manage to fix it updating it for the version 6.0.8. You will need to update BCLib to 1.1.5 too. I had to delete the DIM-1 folder, do it at your own risk.

**Comment by Chuunkyz** [comment]
fixed now
