### ISSUE TITLE
Can't complete "Oak Barrel" quest in 0.4.3

### ISSUE THREAD

**Issue by stephen-smith** [Chuunkyz/BenchmarkII-1.18#20]
Crafting a barrel from oak planks and oak slabs gives a spruce barrel.

"Cheating" in the uncraftable "Oak Barrel" item(s) from Blockus mod, and clicking [Manual Detection] doesn't complete the quest.

**Comment by Zarepheth** [comment]
Same problem.
The only craftable barrel is the Spruce barrel. REI provides no recipes for crafting any initial wooden barrels other than Spruce. Using Oak planks and slabs gives the spruce barrel.

**Comment by Zarepheth** [comment]
In version 0.5.2, I am still having this problem - at least in my original world (created in version 0.4.5).
None of the Blockus barrels are craftable. And the quest book still had "Oak Barrel" for the first quest of the line.

But... before submitting this comment, I checked every barrel in REI. During which time, I also had a spruce barrel in my inventory. After closing the REI and crafting windows, I suddenly got the quest completion -- and the quest book had updated to requiring a Spruce Barrel!
That is totally weird!

Anyway, if anyone else has this problem, put a spruce barrel in your inventory and look around in REI while on a crafting grid menu. It may reset the quest book for the newest updates and allow the quest to complete.
