### ISSUE TITLE
Hovering mouse over Dank 3 causes crash to desktop.

### ISSUE THREAD

**Issue by Zarepheth** [Chuunkyz/BenchmarkII-1.18#29]
I have a Dank 3 storage item in my inventory. When my mouse cursor passes over it, I suffer a crash to desktop.

Crash log:
[crash-2022-01-06_22.45.14-client.txt](https://github.com/Chuunkyz/BenchmarkII-1.18/files/7826551/crash-2022-01-06_22.45.14-client.txt)

**Comment by Zarepheth** [comment]
ClassCastException
Dank storage tooltip cannot be cast to some other class.
Not Enough Crashes deobsfuscating indicates that the IceBerg library is doing something at the time of failure. I'm just guessing that the two mods had a conflict...

**Comment by Zarepheth** [comment]
Reverting to modpack version 0.4.8 allows me to use the Dank without crashing.

I am guessing some changes in updated mods are causing conflicts with each other.

**Comment by nickalbrecht** [comment]
At first glance, it looks like I was able to get around this bug by enabling content management for the Benchmark II profile in the CurseForge app.  Then simply update the version of Iceberg to the most recent on it's own while you wait for an update to the pack. So far this has worked for me. This way, you don't have to revert to 0.4.8

**Comment by Zarepheth** [comment]
I tried that, but the the latest release versions of Dank Storage and Iceberg (as of that time) I was still suffering crashes.
However, if either mod was updated since... then perhaps they'll work.
I can test it sometime tomorrow.

**Comment by Neocentric** [comment]
Just had this happen to me as well.  Will try updating Iceberg and see if it solves the issue.

**Comment by Neocentric** [comment]
> At first glance, it looks like I was able to get around this bug by enabling content management for the Benchmark II profile in the CurseForge app. Then simply update the version of Iceberg to the most recent on it's own while you wait for an update to the pack. So far this has worked for me. This way, you don't have to revert to 0.4.8

Can confirm that this worked for me

**Comment by Zarepheth** [comment]
The most recent modpack version 0.5.2 fixed the Dank problem.

On a separate note...
Updating the modpack resets my HUD, Map, and some other settings. But this probably belongs in a separate issue.
