### ISSUE TITLE
Cannot complete storage quest - Dank 3

### ISSUE THREAD

**Issue by Zarepheth** [Chuunkyz/BenchmarkII-1.18#34]
Although I have two Dank 3's, neither registers for completing the quest.

I'm not sure, but I think the quest requires a Dank that has never been used. I'm a bit strapped for materials, so it may be a while before I've enough gold to create a new Dank get it to level 3.

Modpack version 0.5.2.

**Comment by Chuunkyz** [comment]
there's a new quest mod now
