### ISSUE TITLE
Carrier Doesn't Work

### ISSUE THREAD

**Issue by 8bitsam** [Chuunkyz/BenchmarkII-1.18#37]
Pretty much the title. Using the carrier keybind to try to pick up a chest doesn't work, nor does shift+right click. When I go into the config and change it to require the glove, shift+right click works (with the glove on), but the carrier keybind doesn't.

**Comment by Chuunkyz** [comment]
i just changed the default keybind, shift right click conflicts with a lot of other mods
you can use what you want in the controls
