### ISSUE TITLE
Totem of undying unobtainable

### ISSUE THREAD

**Issue by jezzen** [Chuunkyz/BenchmarkII-1.18#40]
Totemic overhaul replaces evoker drops with custom totems, so unless there's another method to obtain vanilla totems of undying that I'm unaware of there are several uncraftable items.

**Comment by jezzen** [comment]
Just recalled that 1 does generate in the large graveyard. Still very rare, but would be up to you on whether it's enough for the few  items that need it.

**Comment by Chuunkyz** [comment]
you can make a totem of undying with the one from totemic overhaul, check the book to see how to make it
i'll change the totem in the chests with a totemic overhaul one with the undying thing

**Comment by jezzen** [comment]
The whole point of what I'm talking about is that you currently need the vanilla totem for crafting recipes. Slotlink, hearty trinkets, deep mob learning and bewitchment each have an item needing a totem to craft. If you end up removing the totem you need to also change the recipes or they become unobtainable.
