### ISSUE TITLE
Cannot craft Lectern with vanilla items 0.6.0

### ISSUE THREAD

**Issue by mnsnownutt** [Chuunkyz/BenchmarkII-1.18#41]
As the title notes, using 0.6.0 of the modpack and you cannot craft a lectern with vanilla bookshelves and slabs.  Need to use BYG bookshelves and slabs, Better End bookshelves and slabs or Valleycraft.  I looked through the change notes for later revisions, but did not see anything specifically regarding this.

EDIT - since none of the BYG biomes generate, none of the wood types generate, making it impossible to craft lecterns without going to the End.

**Comment by Chuunkyz** [comment]
i'll not support 0.6.0, sorry

**Comment by mnsnownutt** [comment]
Got it.

So, does that mean it was fixed in later versions, or do I need to install a later version and resubmit the same bug report for a later version?
