### ISSUE TITLE
0.6.4 Quests are not registering

### ISSUE THREAD

**Issue by mnsnownutt** [Chuunkyz/BenchmarkII-1.18#43]
When you complete something (make a barrel, chest, iron chest, etc.) that is listed in the quest book, nothing happens.  Previous versions it automatically recognized and registered the event.  Even if you delve into the item and try and hit submit, the submit button is inoperable.
Here is just one example. 
![2022-01-21_15 36 19](https://user-images.githubusercontent.com/31514693/150603312-d996657d-ecac-4136-af05-7de85814f395.png)
.

EDIT - I would note that an advancement notification pops up on the screen, but when you go into the quest book it is not there.

**Comment by galori** [comment]
Did you unlock the "Storage and Furnaces" chapter in the "Unlock Chapters" section? 

<img src="https://user-images.githubusercontent.com/70486/152697336-8b5080d9-a65b-4dbe-899c-9f1c95311b8b.png" width=300>
<img src="https://user-images.githubusercontent.com/70486/152697400-06888e6b-5964-4038-83a3-c5abe86aefbb.png" width=300>

**Comment by mnsnownutt** [comment]
Do you mean manually unlock it?  I do not remember if I tried that.  I will check when I get a chance later today.  I have probably crafted 100+ chests, a dozen iron chests, etc., so I would assume that would register, unless you need to manually do it now.

Edit - I forgot, I stopped with 0.6.4 version a couple of weeks ago, due to the bugs in some of the mods and deleted everything.  I am just going to close this out.  It also happens in the 0.6.0 version, but I know that is no longer supported, even though it is less than a month old.
