### ISSUE TITLE
0.6.4 - Cannot equip Inmis Frayed Backpack

### ISSUE THREAD

**Issue by mnsnownutt** [Chuunkyz/BenchmarkII-1.18#44]
Per the title, cannot equip it on your back in the backpack slot, or even in the armor slot.  It will only go in your inventory.

**Comment by Chuunkyz** [comment]
the backpack is not a trinket anymore, idk if that's intended

**Comment by mnsnownutt** [comment]
Weird.  Worked just fine in 0.6.0 of the mod pack.

**Comment by Chuunkyz** [comment]
because i updated the mod and it's not a trinket _anymore_

**Comment by Zarepheth** [comment]
About two days ago, I updated the mod in my curse profile for this modpack, and was again able to equip the backpack in a trinket slot. I suspect the mod author made some changes that impaired compatibility and later additional changes restored compatibility.
