### ISSUE TITLE
0.6.4 - BYG trees will not grow from saplings

### ISSUE THREAD

**Issue by mnsnownutt** [Chuunkyz/BenchmarkII-1.18#45]
As noted, cannot grow BYG trees from saplings.  I tried the fir trees and noticed nothing was happening.  Went into a creative world and I tested the red birch, white cherry, maple, fir ... none of them will grow when spamming them with bone meal.

**Comment by Chuunkyz** [comment]
that's up to byg to implement this, not my problem, sorry
