### ISSUE TITLE
Circular recipe with End Stone Smelter and Thallasium Ingots

### ISSUE THREAD

**Issue by Seegras** [Chuunkyz/BenchmarkII-1.18#46]
End Stone Smelter requires Thallasium Ingots which require an End Stone Smelter to smelt the Raw Thallasium to produce Thallasium Ingots. 

Or are they meant being found/looted from structures?

**Comment by Chuunkyz** [comment]
most likely something not intended by the better end dev, i'll see what i can do about it

**Comment by Chuunkyz** [comment]
fixed in next update
