### ISSUE TITLE
Carrying Glove from Carrier has no recipe

### ISSUE THREAD

**Issue by Seegras** [Chuunkyz/BenchmarkII-1.18#48]
Carrying Glove from Carrier has no recipe. Unless it's supposed to be found somewhere, the glove can't be gotten and the quest is not solvable.

**Comment by Chuunkyz** [comment]
will be fixed in next update !

**Comment by Seegras** [comment]
Not fixed yet.

**Comment by Chuunkyz** [comment]
yea, there's currently a problem with it, sorry for the inconvenience, i'll try to fix it in the next big update (not 0.6.8)
