### ISSUE TITLE
Probable conflict with Totemic Overhaul Totems and recipes

### ISSUE THREAD

**Issue by Seegras** [Chuunkyz/BenchmarkII-1.18#49]
Totemic Overhaul replaces the Totems of Undying that get dropped by Evokers with "Active Totem". You can make these yourself, as well as the "Passive Totem". 

The trouble is, the recipes for "Multi Demensional Remote", "Illager Data Model" and "Blue Heart Crystal" expect the vanilla "Totem of Undying" (which might or might not be impossible to get; I've not yet tried everything, I just got my first totem from an Evoker, which won't drop vanilla totems any more according to the Totemic Overhaul mod).

**Comment by Chuunkyz** [comment]
thanx for reporting, these recipes will be fixed !

**Comment by Seegras** [comment]
Not yet fixed, tried with Active Totem, Passive Totem, Blank Totem and Enchanted Totem of Undying gotten from loot. 

Just saw, this is a duplicate of #40
