### ISSUE TITLE
spawning graves crashes client and area stops loading in a 2 chunk radius when on server.

### ISSUE THREAD

**Issue by internet-person** [Chuunkyz/BenchmarkII-1.18#5]
_original post deleted for my sanity because im incapable of writing a whole post in one try without sounding stupid._

the area around the grave does not load visually, and near the middle doesnt load functionally either. you will become stuck if you walk into the area if you cannot fly. as such this is kinda server breaking.

this issue has been patched in the current update of the mod, please include this revision whenever the pack is updated next.

**Comment by internet-person** [comment]
this has been reported to the mod dev and ive managed to work around it fine by removing it server side without causing any issues, so im not expecting anything from you on this. just wanted to make you aware that something funky was going on.

**Comment by bobstar3233** [comment]
Roumor has it theres an update later today that should fix it

**Comment by internet-person** [comment]
thank you!
