### ISSUE TITLE
Magic Fungi Spells don't register as quests

### ISSUE THREAD

**Issue by Seegras** [Chuunkyz/BenchmarkII-1.18#57]
Spells made on Magic Fungi Spell Discovery Workbench don't register as quests done.

Neither did Impetus Sword, Morbus Scythe, Clypeus Shield and Utilis Pickaxe

**Comment by Chuunkyz** [comment]
i'll check this, but be sure to unlock the chapters

**Comment by Seegras** [comment]
Addendum: I think the reason was that the Fungi Spell Discovery Workbench didn't register correctly. Fixed.
