### ISSUE TITLE
Why not send a complete server package? ?I can't download the server package.

### ISSUE THREAD

**Issue by ningnaa** [Chuunkyz/BenchmarkII-1.18#58]
I can't download the server package.Why not send a complete server package? ?Error in downloading. Just like in the picture.What should I .Can someone who can help me?Thank you very much.
![LC_BMTQ(E%E0H3I VXCKU99](https://user-images.githubusercontent.com/98951374/152329798-1a7fb4a1-3ed4-4fb6-95db-f28300aca01e.png)

**Comment by Chuunkyz** [comment]
PrObLeMs wItH tHe _**INTERNET CONNECTION**_
