### ISSUE TITLE
Suggestion: add Roughly Enough Resources mod for JEI

### ISSUE THREAD

**Issue by galori** [Chuunkyz/BenchmarkII-1.18#61]
Its a Fabric mod and updated for 1.18, and it seems to work.

https://www.curseforge.com/minecraft/mc-mods/roughly-enough-resources

**Comment by Chuunkyz** [comment]
it's uncofigurable and looks like a debug mode with the ids everywhere
plus it shows block drops, including every unobtainable thing
so not for the moment, sorry
