### ISSUE TITLE
performance with REI and broken creative items

### ISSUE THREAD

**Issue by ZikViM** [Chuunkyz/BenchmarkII-1.18#68]
Sorry if my english is bad.
I have a huge performance problem with using REI in inventory, FPS just dropping down immediately when i open E from 140-160 to 30-40 and normalized when right bar is empty or inventory be closed. How can i fix that? Also idk why but i have a missing item or block which i could use to exchange to creative items in creative tab in questbook, instead of this i had a ? who named benchmarkadditions:benchmark_core
![javaw_gMVhNPjEZ6](https://user-images.githubusercontent.com/64686430/154534266-dbfa8ce3-c76d-4255-b399-5b1fb46d0340.png)
![VZLXOVesKj](https://user-images.githubusercontent.com/64686430/154534279-c5a07861-c6d0-440b-a92b-421ce801b3bd.png)
![YrYArQbXby](https://user-images.githubusercontent.com/64686430/154534287-b75e2d3e-4895-416c-bf9a-68e86c8daaa5.png)

**Comment by Chuunkyz** [comment]
the performance issues should be fixed now
for the creative chapter, it's normal, it's not fully implemented yet
