### ISSUE TITLE
FTB Ultimine not present on server

### ISSUE THREAD

**Issue by katlyn** [Chuunkyz/BenchmarkII-1.18#69]
Both 0.6.9 and 0.6.10 (the latest version at the time of writing) do not include FTB Ultimine in their server distributions, making vein mining on servers impossible. Manually adding the mod to the server pack causes a crash with the same error as in #64. Not being able to vein mine on servers is fairly annoying and considerably worsens player experience.

**Comment by Chuunkyz** [comment]
that's normal, ftb ultimine doesnt work on servers actually
you can grab a modified version of ftb ultimine to fix that on my discord
