### ISSUE TITLE
Unexpected initial spawn locations in new world.

### ISSUE THREAD

**Issue by Zarepheth** [Chuunkyz/BenchmarkII-1.18#70]
Probably poor luck, but I thought Minecraft's vanilla spawning algorithm would prevent these types of initial spawns.

For my first 0.6.8 world, I spawned on top of a tree!
![2022-02-09_21 07 40](https://user-images.githubusercontent.com/22124796/154753502-8f344873-4f59-4acf-801d-c238011d7d5a.png)
World seed: -1604606020505790055

For my next world, after updating to modpack version 0.6.10, I spawned on the "bones" of a structure in the middle of the ocean!
![2022-02-13_15 55 53](https://user-images.githubusercontent.com/22124796/154753742-3913625a-889d-4d67-9101-d5709d3386b7.png)
![2022-02-13_15 56 53](https://user-images.githubusercontent.com/22124796/154753839-c791c036-70a9-4e8a-8f86-93c14d773644.png)
World seed: -999023740346150211

**Comment by Chuunkyz** [comment]
i can't really do much about this, however the bones structure is going to be rarer in next update

**Comment by Zarepheth** [comment]
I wasn't sure if you could do anything, but I found these two initial spawns to be extremely unusual (and rather difficult as starting locations) and thought people might want to see what sort of places Minecraft (with mods) might place them!
