### ISSUE TITLE
[BUG] Recycler put my world on crash loop

### ISSUE THREAD

**Issue by MisterZam** [Chuunkyz/BenchmarkII-1.18#71]
After putting the recycler beside the Iron Furnace Wireless source thingy, I crashed and cannot log in to the world anymore.

Crash Log:
https://pastebin.com/b4easEjE

**Comment by Chuunkyz** [comment]
report to indrev and iron furnaces
also remove iron furnaces, log into your world and re-add it to re-use your world, or use something to remove the block from the world
