### ISSUE TITLE
Botania Livingwood Twig is uncraftable

### ISSUE THREAD

**Issue by GrokDuckFarmer** [Chuunkyz/BenchmarkII-1.18#85]
Playing with version 1.0.0 on a server, and I can't craft the Livingwood Twig.  Recipe shows using Livingwood Logs, but two give me 16 sticks instead of 1 Livingwood Twig.  Are there crafting table equivalents that allow for multiple recipe outputs?  The vanilla crafting table does not.

I confirmed that the recipe is there by installing Polymorph and confirming that there is both a 16 sticks and 1 Livingwood Twig recipes currently in the pack.

**Comment by Chuunkyz** [comment]
fixed in next version
