### ISSUE TITLE
Enchants applied via anvil are always the default maximum

### ISSUE THREAD

**Issue by VulpineMalware** [Chuunkyz/BenchmarkII-1.18#90]
https://user-images.githubusercontent.com/82441730/160107831-ad0abd7e-6e78-4fd4-97f8-b3cac9926b75.mp4

No clue what is causing this to happen, I'm playing on the most recent release without any changes.
It doesn't matter if survival, creative, op'd, or not

**Comment by Chuunkyz** [comment]
mmh, i'll find what mod causes this and fix for next update

**Comment by Chuunkyz** [comment]
fixed
