### ISSUE TITLE
TheOneProbe causes consistent crash when looking at a shulker

### ISSUE THREAD

**Issue by VulpineMalware** [Chuunkyz/BenchmarkII-1.18#93]
Title says it all, here's a crash log for it as well

[crash-2022-03-25_19.18.20-client.txt](https://github.com/Chuunkyz/BenchmarkII-1.18/files/8354539/crash-2022-03-25_19.18.20-client.txt)

**Comment by Chuunkyz** [comment]
known issue, fixed in next update
