### ISSUE TITLE
Server crashing on player attempting to load in

### ISSUE THREAD

**Issue by Keatonjinks** [Chuunkyz/BenchmarkII-1.18#94]
Getting stackoverflowerrornull when trying to load in the game. It causes the server to crash and the console spams player advancement tracker 344 and 348 a lot. I cleared my player data and it keeps happening.

**Comment by Keatonjinks** [comment]
I was able to login after deleting my player data and reloading the server but now that won’t work. Still spamming the advancement problem on attempting to login.

**Comment by Chuunkyz** [comment]
fixed in next update
