### ISSUE TITLE
Error after entering in the world

### ISSUE THREAD

**Issue by theantonyis** [Chuunkyz/BenchmarkII-1.18#99]
![image](https://user-images.githubusercontent.com/28813689/160709845-06d0d246-f478-4d08-82ff-b4588ba5269e.png)
Sorry for text in russian, but this problem has appeared after i updated my modpack to 1.0.5 version.

**Comment by Chuunkyz** [comment]
you have to reset the nether, also be sure to remove/reinstall the modpack in the launcher, that's not safe to "update"

**Comment by theantonyis** [comment]
it's worked! thanks for your help. i'll be waiting for new updates ;)
